# password: 12345678  # emails: alf1@mail.ru, alf2@mail.ru, alf3@mail.ru...

insert into persons (about, birth_date, confirmation_code, email, first_name, approval, block,
                     last_name, last_online_time, message_permission, password, phone, photo, registration_date, city_id, country_id)
VALUES ('About me',
        '1970/10/28',
        'confirmation',
        'alf1@mail.ru',
        'Alf',
        'APPROVED',
        'UNBLOCKED',
        'The Alien',
        '1990/03/24',
        'ALL',
        '$2y$12$H37gSt8zlH1qkPqYVPByXO2bsSVkcDfSgwcJlyTobzdLPvRx3yzne',
        '+79990000001',
        '/img/ALF01.jpg',
        '1986/09/22',
        null,
        null);

insert into persons (about, birth_date, confirmation_code, email, first_name, approval, block,
                     last_name, last_online_time, message_permission, password, phone, photo, registration_date, city_id, country_id)
VALUES ('I like cats',
        '1970/10/28',
        'confirmation',
        'alf2@mail.ru',
        'Alf',
        'APPROVED',
        'UNBLOCKED',
        'The Alien',
        '1990/03/24',
        'ALL',
        '$2y$12$H37gSt8zlH1qkPqYVPByXO2bsSVkcDfSgwcJlyTobzdLPvRx3yzne',
        '+79990000001',
        '/img/ALF01.jpg',
        '1986/09/22',
        null,
        null);

insert into persons (about, birth_date, confirmation_code, email, first_name, approval, block,
                     last_name, last_online_time, message_permission, password, phone, photo, registration_date, city_id, country_id)
VALUES ('I like beer',
        '1970/10/28',
        'confirmation',
        'alf3@mail.ru',
        'Alf',
        'APPROVED',
        'UNBLOCKED',
        'The Alien',
        '1990/03/24',
        'ALL',
        '$2y$12$H37gSt8zlH1qkPqYVPByXO2bsSVkcDfSgwcJlyTobzdLPvRx3yzne',
        '+79990000001',
        '/img/ALF01.jpg',
        '1986/09/22',
        null,
        null);

insert into persons (about, birth_date, confirmation_code, email, first_name, approval, block,
                     last_name, last_online_time, message_permission, password, phone, photo, registration_date, city_id, country_id)
VALUES ('I love Melmac',
        '1970/10/28',
        'confirmation',
        'alf4@mail.ru',
        'Gordon',
        'APPROVED',
        'UNBLOCKED',
        'Shumway',
        '1990/03/24',
        'ALL',
        '$2y$12$H37gSt8zlH1qkPqYVPByXO2bsSVkcDfSgwcJlyTobzdLPvRx3yzne',
        '+79990000001',
        '/img/ALF01.jpg',
        '1986/09/22',
        null,
        null);