ALTER TABLE post_comments DROP COLUMN parent_id;
ALTER TABLE post_comments ADD parent_id INTEGER NULL;

INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (1, null, 'Текст коммента', '2020/11/26', 2, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (2, null, 'Текст коммента', '2020/11/07', 2, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (3, null, 'Текст коммента', '2020/01/08', 4, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (4, 3, 'Текст коммента в ответ на коммент', '2020/01/08', 1, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (5, null, 'Текст коммента', '2020/11/25', 2, 24, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (6, null, 'Текст коммента', '2020/02/14', 3, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (7, null, 'Текст коммента', '2020/11/21', 1, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (8, null, 'Текст коммента', '2020/10/07', 1, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (9, 8, 'Текст коммента в ответ на коммент', '2020/10/07', 2, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (10, null, 'Текст коммента', '2020/04/05', 1, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (11, null, 'Текст коммента', '2020/01/02', 2, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (12, null, 'Текст коммента', '2020/07/22', 4, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (13, null, 'Текст коммента', '2020/12/21', 4, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (14, null, 'Текст коммента', '2020/12/02', 2, 32, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (15, null, 'Текст коммента', '2020/07/16', 3, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (16, null, 'Текст коммента', '2020/03/17', 2, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (17, null, 'Текст коммента', '2020/07/15', 2, 13, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (18, null, 'Текст коммента', '2020/03/05', 4, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (19, null, 'Текст коммента', '2020/03/13', 3, 19, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (20, null, 'Текст коммента', '2020/04/06', 3, 34, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (21, null, 'Текст коммента', '2020/02/26', 4, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (22, null, 'Текст коммента', '2020/05/11', 2, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (23, null, 'Текст коммента', '2020/01/21', 3, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (24, null, 'Текст коммента', '2020/10/02', 4, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (25, null, 'Текст коммента', '2020/02/17', 1, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (26, 25, 'Текст коммента в ответ на коммент', '2020/02/17', 4, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (27, null, 'Текст коммента', '2020/10/25', 3, 17, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (28, null, 'Текст коммента', '2020/11/05', 3, 17, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (29, null, 'Текст коммента', '2020/01/12', 1, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (30, null, 'Текст коммента', '2020/11/06', 1, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (31, null, 'Текст коммента', '2020/06/20', 3, 19, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (32, null, 'Текст коммента', '2020/06/20', 3, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (33, 32, 'Текст коммента в ответ на коммент', '2020/06/20', 4, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (34, null, 'Текст коммента', '2020/01/08', 4, 35, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (35, null, 'Текст коммента', '2020/11/02', 3, 32, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (36, null, 'Текст коммента', '2020/01/01', 2, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (37, null, 'Текст коммента', '2020/02/06', 3, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (38, null, 'Текст коммента', '2020/07/21', 4, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (39, null, 'Текст коммента', '2020/06/11', 2, 22, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (40, null, 'Текст коммента', '2020/07/09', 4, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (41, 40, 'Текст коммента в ответ на коммент', '2020/07/09', 1, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (42, null, 'Текст коммента', '2020/06/14', 1, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (43, null, 'Текст коммента', '2020/04/12', 1, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (44, null, 'Текст коммента', '2020/11/06', 3, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (45, null, 'Текст коммента', '2020/07/11', 4, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (46, null, 'Текст коммента', '2020/03/12', 4, 34, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (47, 46, 'Текст коммента в ответ на коммент', '2020/03/12', 4, 34, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (48, null, 'Текст коммента', '2020/01/09', 4, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (49, null, 'Текст коммента', '2020/07/18', 2, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (50, null, 'Текст коммента', '2020/06/26', 4, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (51, 50, 'Текст коммента в ответ на коммент', '2020/06/26', 3, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (52, null, 'Текст коммента', '2020/03/01', 3, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (53, null, 'Текст коммента', '2020/07/15', 3, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (54, null, 'Текст коммента', '2020/08/05', 4, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (55, null, 'Текст коммента', '2020/09/03', 3, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (56, null, 'Текст коммента', '2020/04/03', 3, 13, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (57, null, 'Текст коммента', '2020/06/13', 2, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (58, null, 'Текст коммента', '2020/01/09', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (59, 58, 'Текст коммента в ответ на коммент', '2020/01/09', 3, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (60, null, 'Текст коммента', '2020/07/07', 4, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (61, 60, 'Текст коммента в ответ на коммент', '2020/07/07', 3, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (62, null, 'Текст коммента', '2020/01/15', 2, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (63, null, 'Текст коммента', '2020/04/24', 3, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (64, null, 'Текст коммента', '2020/06/05', 2, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (65, null, 'Текст коммента', '2020/04/09', 3, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (66, null, 'Текст коммента', '2020/07/25', 2, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (67, 66, 'Текст коммента в ответ на коммент', '2020/07/25', 3, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (68, null, 'Текст коммента', '2020/04/25', 1, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (69, null, 'Текст коммента', '2020/08/05', 1, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (70, null, 'Текст коммента', '2020/07/10', 4, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (71, null, 'Текст коммента', '2020/06/12', 4, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (72, null, 'Текст коммента', '2020/05/09', 2, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (73, null, 'Текст коммента', '2020/06/23', 3, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (74, null, 'Текст коммента', '2020/07/19', 4, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (75, null, 'Текст коммента', '2020/12/07', 2, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (76, null, 'Текст коммента', '2020/01/10', 2, 17, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (77, null, 'Текст коммента', '2020/04/17', 2, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (78, 77, 'Текст коммента в ответ на коммент', '2020/04/17', 4, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (79, null, 'Текст коммента', '2020/01/12', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (80, null, 'Текст коммента', '2020/02/26', 3, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (81, null, 'Текст коммента', '2020/04/24', 4, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (82, null, 'Текст коммента', '2020/11/27', 3, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (83, null, 'Текст коммента', '2020/09/02', 4, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (84, null, 'Текст коммента', '2020/02/07', 3, 35, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (85, null, 'Текст коммента', '2020/10/08', 3, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (86, null, 'Текст коммента', '2020/04/01', 3, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (87, 86, 'Текст коммента в ответ на коммент', '2020/04/01', 4, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (88, null, 'Текст коммента', '2020/12/03', 4, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (89, null, 'Текст коммента', '2020/04/08', 4, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (90, 89, 'Текст коммента в ответ на коммент', '2020/04/08', 3, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (91, null, 'Текст коммента', '2020/04/25', 1, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (92, null, 'Текст коммента', '2020/08/18', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (93, null, 'Текст коммента', '2020/04/13', 4, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (94, null, 'Текст коммента', '2020/07/03', 3, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (95, null, 'Текст коммента', '2020/07/22', 3, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (96, null, 'Текст коммента', '2020/07/23', 4, 3, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (97, 96, 'Текст коммента в ответ на коммент', '2020/07/23', 4, 3, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (98, null, 'Текст коммента', '2020/06/21', 2, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (99, 98, 'Текст коммента в ответ на коммент', '2020/06/21', 3, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (100, null, 'Текст коммента', '2020/05/22', 2, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (101, null, 'Текст коммента', '2020/04/05', 4, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (102, null, 'Текст коммента', '2020/01/02', 1, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (103, null, 'Текст коммента', '2020/02/12', 1, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (104, null, 'Текст коммента', '2020/08/17', 4, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (105, null, 'Текст коммента', '2020/01/22', 1, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (106, null, 'Текст коммента', '2020/01/23', 1, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (107, null, 'Текст коммента', '2020/03/12', 3, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (108, 107, 'Текст коммента в ответ на коммент', '2020/03/12', 1, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (109, null, 'Текст коммента', '2020/08/09', 3, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (110, null, 'Текст коммента', '2020/08/01', 2, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (111, null, 'Текст коммента', '2020/11/17', 3, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (112, 111, 'Текст коммента в ответ на коммент', '2020/11/17', 3, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (113, null, 'Текст коммента', '2020/12/21', 3, 34, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (114, null, 'Текст коммента', '2020/12/08', 3, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (115, null, 'Текст коммента', '2020/10/22', 3, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (116, null, 'Текст коммента', '2020/05/01', 3, 35, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (117, null, 'Текст коммента', '2020/07/06', 4, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (118, null, 'Текст коммента', '2020/10/16', 2, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (119, null, 'Текст коммента', '2020/12/15', 1, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (120, null, 'Текст коммента', '2020/11/20', 3, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (121, null, 'Текст коммента', '2020/07/11', 4, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (122, null, 'Текст коммента', '2020/09/26', 1, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (123, null, 'Текст коммента', '2020/08/18', 3, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (124, 123, 'Текст коммента в ответ на коммент', '2020/08/18', 2, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (125, null, 'Текст коммента', '2020/10/01', 1, 3, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (126, null, 'Текст коммента', '2020/03/24', 2, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (127, null, 'Текст коммента', '2020/03/13', 2, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (128, null, 'Текст коммента', '2020/01/06', 4, 40, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (129, null, 'Текст коммента', '2020/11/19', 2, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (130, null, 'Текст коммента', '2020/09/23', 2, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (131, null, 'Текст коммента', '2020/04/19', 1, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (132, null, 'Текст коммента', '2020/09/12', 3, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (133, 132, 'Текст коммента в ответ на коммент', '2020/09/12', 2, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (134, null, 'Текст коммента', '2020/04/27', 3, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (135, null, 'Текст коммента', '2020/10/19', 1, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (136, null, 'Текст коммента', '2020/07/19', 2, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (137, 136, 'Текст коммента в ответ на коммент', '2020/07/19', 4, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (138, null, 'Текст коммента', '2020/12/09', 1, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (139, 138, 'Текст коммента в ответ на коммент', '2020/12/09', 1, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (140, null, 'Текст коммента', '2020/04/02', 3, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (141, null, 'Текст коммента', '2020/07/20', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (142, null, 'Текст коммента', '2020/03/09', 1, 34, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (143, null, 'Текст коммента', '2020/01/05', 2, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (144, null, 'Текст коммента', '2020/01/13', 3, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (145, null, 'Текст коммента', '2020/07/23', 2, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (146, null, 'Текст коммента', '2020/01/05', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (147, null, 'Текст коммента', '2020/12/22', 1, 3, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (148, null, 'Текст коммента', '2020/11/08', 1, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (149, null, 'Текст коммента', '2020/02/20', 4, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (150, null, 'Текст коммента', '2020/10/20', 4, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (151, null, 'Текст коммента', '2020/03/11', 1, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (152, null, 'Текст коммента', '2020/12/03', 3, 3, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (153, null, 'Текст коммента', '2020/04/02', 3, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (154, null, 'Текст коммента', '2020/01/20', 2, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (155, null, 'Текст коммента', '2020/02/20', 3, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (156, 155, 'Текст коммента в ответ на коммент', '2020/02/20', 1, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (157, null, 'Текст коммента', '2020/02/25', 3, 32, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (158, 157, 'Текст коммента в ответ на коммент', '2020/02/25', 2, 32, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (159, null, 'Текст коммента', '2020/08/14', 4, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (160, null, 'Текст коммента', '2020/04/03', 3, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (161, null, 'Текст коммента', '2020/04/15', 3, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (162, null, 'Текст коммента', '2020/08/25', 2, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (163, null, 'Текст коммента', '2020/04/10', 3, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (164, 163, 'Текст коммента в ответ на коммент', '2020/04/10', 2, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (165, null, 'Текст коммента', '2020/05/01', 2, 22, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (166, null, 'Текст коммента', '2020/01/05', 3, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (167, null, 'Текст коммента', '2020/01/04', 4, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (168, null, 'Текст коммента', '2020/11/15', 3, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (169, null, 'Текст коммента', '2020/12/23', 1, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (170, null, 'Текст коммента', '2020/12/03', 3, 17, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (171, null, 'Текст коммента', '2020/09/04', 3, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (172, null, 'Текст коммента', '2020/11/08', 3, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (173, null, 'Текст коммента', '2020/10/21', 4, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (174, null, 'Текст коммента', '2020/05/01', 2, 38, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (175, null, 'Текст коммента', '2020/10/14', 1, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (176, null, 'Текст коммента', '2020/04/01', 1, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (177, null, 'Текст коммента', '2020/05/06', 3, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (178, null, 'Текст коммента', '2020/10/05', 4, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (179, null, 'Текст коммента', '2020/12/01', 2, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (180, null, 'Текст коммента', '2020/02/27', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (181, null, 'Текст коммента', '2020/03/20', 4, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (182, 181, 'Текст коммента в ответ на коммент', '2020/03/20', 2, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (183, null, 'Текст коммента', '2020/06/15', 4, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (184, null, 'Текст коммента', '2020/06/16', 1, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (185, 184, 'Текст коммента в ответ на коммент', '2020/06/16', 2, 8, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (186, null, 'Текст коммента', '2020/08/27', 4, 13, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (187, null, 'Текст коммента', '2020/06/20', 1, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (188, null, 'Текст коммента', '2020/03/25', 4, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (189, null, 'Текст коммента', '2020/08/12', 1, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (190, null, 'Текст коммента', '2020/01/14', 1, 17, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (191, null, 'Текст коммента', '2020/10/25', 4, 22, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (192, null, 'Текст коммента', '2020/01/17', 1, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (193, 192, 'Текст коммента в ответ на коммент', '2020/01/17', 3, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (194, null, 'Текст коммента', '2020/04/21', 1, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (195, null, 'Текст коммента', '2020/01/03', 4, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (196, null, 'Текст коммента', '2020/04/03', 3, 40, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (197, null, 'Текст коммента', '2020/05/21', 3, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (198, 197, 'Текст коммента в ответ на коммент', '2020/05/21', 3, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (199, null, 'Текст коммента', '2020/06/23', 1, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (200, null, 'Текст коммента', '2020/12/23', 2, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (201, 200, 'Текст коммента в ответ на коммент', '2020/12/23', 1, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (202, null, 'Текст коммента', '2020/02/16', 1, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (203, null, 'Текст коммента', '2020/03/17', 1, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (204, null, 'Текст коммента', '2020/07/13', 1, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (205, null, 'Текст коммента', '2020/03/08', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (206, 205, 'Текст коммента в ответ на коммент', '2020/03/08', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (207, null, 'Текст коммента', '2020/08/19', 4, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (208, null, 'Текст коммента', '2020/05/05', 2, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (209, null, 'Текст коммента', '2020/04/11', 3, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (210, null, 'Текст коммента', '2020/06/02', 1, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (211, null, 'Текст коммента', '2020/02/14', 2, 18, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (212, null, 'Текст коммента', '2020/03/15', 1, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (213, null, 'Текст коммента', '2020/06/07', 1, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (214, null, 'Текст коммента', '2020/09/26', 1, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (215, null, 'Текст коммента', '2020/01/19', 1, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (216, null, 'Текст коммента', '2020/10/25', 2, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (217, null, 'Текст коммента', '2020/09/13', 4, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (218, null, 'Текст коммента', '2020/04/02', 1, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (219, null, 'Текст коммента', '2020/08/27', 2, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (220, null, 'Текст коммента', '2020/04/26', 4, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (221, null, 'Текст коммента', '2020/12/21', 1, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (222, 221, 'Текст коммента в ответ на коммент', '2020/12/21', 2, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (223, null, 'Текст коммента', '2020/06/16', 1, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (224, 223, 'Текст коммента в ответ на коммент', '2020/06/16', 2, 5, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (225, null, 'Текст коммента', '2020/03/08', 1, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (226, null, 'Текст коммента', '2020/06/02', 1, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (227, null, 'Текст коммента', '2020/07/02', 4, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (228, 227, 'Текст коммента в ответ на коммент', '2020/07/02', 2, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (229, null, 'Текст коммента', '2020/07/20', 2, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (230, null, 'Текст коммента', '2020/02/12', 3, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (231, 230, 'Текст коммента в ответ на коммент', '2020/02/12', 3, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (232, null, 'Текст коммента', '2020/12/02', 4, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (233, null, 'Текст коммента', '2020/04/08', 4, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (234, null, 'Текст коммента', '2020/08/21', 3, 26, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (235, null, 'Текст коммента', '2020/09/06', 3, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (236, null, 'Текст коммента', '2020/02/11', 4, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (237, null, 'Текст коммента', '2020/08/01', 4, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (238, null, 'Текст коммента', '2020/10/03', 1, 6, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (239, null, 'Текст коммента', '2020/01/11', 1, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (240, null, 'Текст коммента', '2020/03/09', 2, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (241, 240, 'Текст коммента в ответ на коммент', '2020/03/09', 4, 37, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (242, null, 'Текст коммента', '2020/05/09', 2, 19, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (243, null, 'Текст коммента', '2020/06/27', 1, 22, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (244, null, 'Текст коммента', '2020/09/02', 1, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (245, null, 'Текст коммента', '2020/04/27', 3, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (246, 245, 'Текст коммента в ответ на коммент', '2020/04/27', 1, 11, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (247, null, 'Текст коммента', '2020/04/03', 2, 4, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (248, null, 'Текст коммента', '2020/01/20', 2, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (249, 248, 'Текст коммента в ответ на коммент', '2020/01/20', 4, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (250, null, 'Текст коммента', '2020/03/11', 2, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (251, null, 'Текст коммента', '2020/07/14', 1, 33, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (252, null, 'Текст коммента', '2020/10/13', 2, 21, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (253, null, 'Текст коммента', '2020/10/12', 4, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (254, null, 'Текст коммента', '2020/02/25', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (255, null, 'Текст коммента', '2020/10/01', 4, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (256, 255, 'Текст коммента в ответ на коммент', '2020/10/01', 4, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (257, null, 'Текст коммента', '2020/05/15', 2, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (258, null, 'Текст коммента', '2020/09/09', 4, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (259, null, 'Текст коммента', '2020/05/09', 2, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (260, null, 'Текст коммента', '2020/01/18', 4, 15, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (261, null, 'Текст коммента', '2020/06/09', 4, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (262, 261, 'Текст коммента в ответ на коммент', '2020/06/09', 1, 2, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (263, null, 'Текст коммента', '2020/09/22', 2, 24, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (264, null, 'Текст коммента', '2020/01/25', 3, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (265, null, 'Текст коммента', '2020/01/16', 2, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (266, null, 'Текст коммента', '2020/08/21', 1, 19, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (267, null, 'Текст коммента', '2020/09/19', 4, 31, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (268, null, 'Текст коммента', '2020/10/03', 2, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (269, null, 'Текст коммента', '2020/04/04', 3, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (270, 269, 'Текст коммента в ответ на коммент', '2020/04/04', 4, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (271, null, 'Текст коммента', '2020/11/08', 3, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (272, null, 'Текст коммента', '2020/06/06', 4, 7, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (273, null, 'Текст коммента', '2020/01/11', 2, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (274, null, 'Текст коммента', '2020/11/06', 1, 35, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (275, null, 'Текст коммента', '2020/06/10', 2, 14, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (276, null, 'Текст коммента', '2020/04/08', 3, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (277, null, 'Текст коммента', '2020/10/02', 4, 40, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (278, 277, 'Текст коммента в ответ на коммент', '2020/10/02', 1, 40, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (279, null, 'Текст коммента', '2020/03/04', 1, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (280, null, 'Текст коммента', '2020/06/26', 3, 9, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (281, null, 'Текст коммента', '2020/02/09', 3, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (282, 281, 'Текст коммента в ответ на коммент', '2020/02/09', 2, 27, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (283, null, 'Текст коммента', '2020/08/08', 4, 29, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (284, null, 'Текст коммента', '2020/09/19', 4, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (285, 284, 'Текст коммента в ответ на коммент', '2020/09/19', 4, 25, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (286, null, 'Текст коммента', '2020/02/17', 1, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (287, null, 'Текст коммента', '2020/07/02', 4, 39, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (288, null, 'Текст коммента', '2020/11/14', 3, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (289, null, 'Текст коммента', '2020/02/25', 4, 36, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (290, null, 'Текст коммента', '2020/11/06', 1, 12, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (291, null, 'Текст коммента', '2020/07/13', 4, 30, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (292, null, 'Текст коммента', '2020/02/05', 3, 20, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (293, null, 'Текст коммента', '2020/10/16', 1, 10, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (294, null, 'Текст коммента', '2020/05/03', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (295, null, 'Текст коммента', '2020/11/10', 4, 1, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (296, null, 'Текст коммента', '2020/06/07', 2, 28, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (297, null, 'Текст коммента', '2020/02/15', 2, 16, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (298, null, 'Текст коммента', '2020/08/16', 2, 23, 'UNBLOCKED');
INSERT INTO post_comments (id, parent_id, text, time, author_id, post_id, block) VALUES (299, null, 'Текст коммента', '2020/02/19', 1, 15, 'UNBLOCKED');

