spring.jpa.hibernate.ddl-auto: validate
spring.datasource.url: jdbc:mysql://localhost:3306/sn_db?serverTimezone=UTC
spring.datasource.username: newroot
spring.datasource.password: idkfa
spring.jpa.show-sql: false
spring.jpa.generate-ddl: false

jwt.token.secret: jwtappgroup
jwt.token.expired: 3600000
jwt.token.test: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGY0QG1haWwucnUiLCJmaXJzdE5hbWUiOiJHb3Jkb24oIzQpIiwibGFzdE5hbWUiOiJTaHVtd2F5IiwiaWF0IjoxNjE0OTE4ODg4LCJleHAiOjE2MTgwNzI0ODh9.C9h6m2jIMbcr_LOH6EuSQ3n4WrciV9_qrkWbfmlkboQ


email:
  host: smtp.gmail.com
  port: 465
  username: java10skillbox@gmail.com
  password: java10rezone

upload:
  path: /home/javapro/javapro-socialnetwork-studygroup-10/uploads

default:
  perPage: 10

limit:
  approval:
    expirationPerSec: 3600
  reset:
    expirationPerSec: 180
  comment:
    lifetimePerSec: 300
  age:
    min: 15

logging:
  logFiles:
    path: /home/javapro/javapro-socialnetwork-studygroup-10/backend/logs

spring.boot.admin.client.url: http://localhost:8081
spring.boot.admin.client.instance.service-url: http://localhost:8080
spring.boot.admin.client.instance.health-url: http://localhost:8080/actuator/health
spring.boot.admin.client.instance.management-url: http://localhost:8080/actuator

management.endpoint.health.show-details: always

spring:
  application:
    name: social-network

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring.boot.admin.client.username: admin
spring.boot.admin.client.password: 12345

notification.lifeMS : 3600000

friend.recommendation.count : 5
